name: Build docs on merge
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build Styleguide documentation
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn styleguide:build

      - name: Deploy Styleguide documentation into github pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          token: ${{ secrets.BOT_PAT }}
          branch: 'main'
          folder: docs-build # The folder that the styleguide:build script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # The folder that we serve our React-Styleguide files from
